### ISSUE TITLE
Issue while playing Arkanoid.

### ISSUE THREAD

**Issue by ddos16** [apiorno/Winter-Examples#2]
Able to successfully start Arkanoid game, while playing I was able to eliminate greenbrick but when ball touches yellow brick I was seeing an error in pharo like attached. please help me.
![pharoarkanoid](https://user-images.githubusercontent.com/39532937/93519419-d905d180-f8f3-11ea-9f05-847de6be4325.PNG)

**Comment by apiorno** [comment]
I already fixed the issue, i will upload now

**Comment by apiorno** [comment]
Try downloading again and let me know if it is fixed

**Comment by ddos16** [comment]
Arkanoid is working fine on Pharo 7 but not on pharo 8. Spider Invasion is not working properly on both instance pharo 7 and 8. attaching screenshot of pharo 7 issue with Spider Invasion but please take a look on pharo 8. For Spider Invasion while clicking on space bar bullet does come. thanks
![pharosparo](https://user-images.githubusercontent.com/39532937/93555671-46d5eb80-f93c-11ea-8afa-2bc19f4d8a45.PNG)

**Comment by apiorno** [comment]
Ok, now is fixed. But there is another known bug: The ship does not shoot

**Comment by ddos16** [comment]
Okay thanks Apiorno, I really appreciate you. I need one more help I have one simple gaming idea. A man will run upwards on a hill and I want to slide few stones towards man, man should be able to escape stones sliding on to him could you please help me build this project. I'm an beginner for pharo please help.

**Comment by ddos16** [comment]
I see Winter-Examples not working on Pharo 8.0 64 bit. please find attached. thanks
![Sparopharo8](https://user-images.githubusercontent.com/39532937/93620735-1cb61500-f9a0-11ea-8a46-d9e196388be0.PNG)

**Comment by apiorno** [comment]
> Okay thanks Apiorno, I really appreciate you. I need one more help I have one simple gaming idea. A man will run upwards on a hill and I want to slide few stones towards man, man should be able to escape stones sliding on to him could you please help me build this project. I'm an beginner for pharo please help.

OK, but first try yourself and the ask me. Your feedback will be of help to me to improve Winter

**Comment by apiorno** [comment]
> I see Winter-Examples not working on Pharo 8.0 64 bit. please find attached. thanks
> ![Sparopharo8](https://user-images.githubusercontent.com/39532937/93620735-1cb61500-f9a0-11ea-8a46-d9e196388be0.PNG)

Which were the actions that led you to the error?

**Comment by ddos16** [comment]
Just followed same process pulled repo from github copied assets folders into image folder and after launching repo from playground i ran spiderInvasion start. Giving me above attached error on Pharo8.0 64 bit

**Comment by apiorno** [comment]
Ok, this is due to some update did to AthensCairo in Pharo8. Will try to fix it soon, try in Pharo7 by the moment

**Comment by ddos16** [comment]
Okay

**Comment by apiorno** [comment]
Hi,
I have been working on this. 
The error was introduced in Pharo8, but fixed in Pharo9, So i removed Pharo8 support and added Pharo9 support.
You can run the examples or create yours using Pharo 7 or Pharo 9.
I will close the issue, if you find something else, create a new one.
Cheers
