### ISSUE TITLE
Instance of OSSDL2WindowHandle did not understand #sdl2Window

### ISSUE THREAD

**Issue by capsulecorplab** [apiorno/Winter-Examples#5]
Running `Do it` on `Arkanoid start`, `SpiderInvasion start`, or `WBA start` triggers the following error

![image](https://user-images.githubusercontent.com/14095576/105281772-bc0f3280-5b61-11eb-92c9-bd04ced4c86d.png)

I'm running Pharo 8.0 (64bit) on Ubuntu 20.04

**Comment by apiorno** [comment]
Hi, in the ReadMe there are labels of support for Pharo 7 and 9, i quited Pharo 8 support because there was a change on Athens Cairo that breaks everything but they fixed it in Pharo 9
