### ISSUE TITLE
#fromSDLSurface: was sent to nil

### ISSUE THREAD

**Issue by capsulecorplab** [apiorno/Winter-Examples#6]
Running `Do it` on `Arkanoid start`, `SpiderInvasion start`, or `WBA start` triggers the following error in Pharo 9.0 (64bit)
![Screenshot from 2021-01-27 10-32-18](https://user-images.githubusercontent.com/14095576/106040389-3e7e8180-608f-11eb-9bb2-c9af02bd7ef5.png)

**Comment by apiorno** [comment]
It is fixed now, you should update the repo of Winter as it was a problem there.

**Comment by capsulecorplab** [comment]
@apiorno Update fixed the issue! Thanks!
